### ISSUE TITLE
Cannot build because of multistep

### ISSUE THREAD

**Issue by ldanielw1** [watson-platform/packer-builder-softlayer#7]
I tried checking out the code here, and installing glide. It gets further then when I try to build leonidlm's version of this plugin, but I get this error:

`src/github.com/watson-platform/packer-builder-softlayer/builder/softlayer/builder.go:203: cannot use commHost (type func("github.com/mitchellh/multistep".StateBag) (string, error)) as type func("github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep".StateBag) (string, error) in field value`
`src/github.com/watson-platform/packer-builder-softlayer/builder/softlayer/builder.go:204: cannot use sshConfig (type func("github.com/mitchellh/multistep".StateBag) (*"golang.org/x/crypto/ssh".ClientConfig, error)) as type func("github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep".StateBag) (*"github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh".ClientConfig, error) in field value`
`src/github.com/watson-platform/packer-builder-softlayer/builder/softlayer/builder.go:206: cannot use new(common.StepProvision) (type *common.StepProvision) as type "github.com/mitchellh/multistep".Step in array or slice literal:`
`	*common.StepProvision does not implement "github.com/mitchellh/multistep".Step (wrong type for Cleanup method)`
&nbsp;&nbsp;&nbsp;&nbsp;`have Cleanup("github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep".StateBag)`
&nbsp;&nbsp;&nbsp;&nbsp;`		want Cleanup("github.com/mitchellh/multistep".StateBag)`

**Comment by litch** [comment]
I JUST downloaded and installed this - it worked fine.  

I DID wind up downloading & setting up BRAND NEW go & glide (I don't usually develop anything in go).  Maybe you just have some crappy state with glide?  Can you clean everything out of there?

**Comment by ldanielw1** [comment]
I just got it to work as well. Secret was that I was on Go 1.7.3, and not 1.6. packer builds fine with go 1.6 now
